"use client";

import { useCallback, useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import { displayValue, formatDate, requestJson, statusLabel } from "../../components/api";

type Review = { id: string; analysis_id: string; request_id: string; question: string; analysis_status: string; status: string; reason: string; recommendation_snapshot: Record<string, unknown>; evidence_snapshot: Array<Record<string, unknown>>; requested_at: string; reviewed_at?: string | null; reviewed_by?: string | null; decision?: string | null; comments?: string | null; decisions: Array<{ decision: string; reviewed_by: string; comments?: string | null; decided_at: string }> };

export default function HumanReviewPage() { const [reviews, setReviews] = useState<Review[]>([]); const [selected, setSelected] = useState<Review | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { try { const next = await requestJson<Review[]>("/api/v1/human-review/inbox?status_filter=pending"); setReviews(next); setSelected((current) => current ? next.find((item) => item.id === current.id) ?? current : next[0] ?? null); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "No pudimos cargar la bandeja."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  return <AppShell><section className="page-hero"><div><span className="eyebrow">GOVERNANCE · {reviews.length} PENDIENTES</span><h1>Human Review, con <em>contexto</em></h1><p>Revisa evidencia y recomendaciones antes de registrar una decisión. Cada acción queda auditada por la API.</p></div><button className="refresh-button" onClick={() => { setLoading(true); void load(); }} aria-label="Actualizar bandeja">↻</button></section>{error && <div className="notice notice--error" role="alert">{error}</div>}{loading ? <div className="loading-panel">Cargando revisiones…</div> : <div className="review-layout"><section className="review-inbox panel"><div className="section-heading"><h2>Inbox</h2><span className="muted">{reviews.length} pendientes</span></div>{reviews.length ? reviews.map((review) => <button key={review.id} className={`review-item ${selected?.id === review.id ? "review-item--active" : ""}`} onClick={() => setSelected(review)}><span className="status-dot status-dot--warning" /><span className="history-copy"><strong>{review.question}</strong><small>{formatDate(review.requested_at)} · {review.reason}</small></span></button>) : <div className="empty-state"><span>✓</span><p>No hay revisiones pendientes.</p></div>}</section>{selected ? <ReviewDetail review={selected} onComplete={load} /> : <div className="welcome-panel"><span className="welcome-icon">◈</span><h2>Bandeja despejada</h2><p>Las revisiones pendientes aparecerán aquí.</p></div>}</div>}</AppShell>; }

function ReviewDetail({ review, onComplete }: { review: Review; onComplete: () => Promise<void> }) { const [reviewer, setReviewer] = useState("reviewer@example.test"); const [comments, setComments] = useState(""); const [confirming, setConfirming] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const decide = async (decision: string) => { setSaving(true); setError(null); try { await requestJson<Review>(`/api/v1/human-review/${review.id}/decision`, { method: "POST", body: JSON.stringify({ decision, reviewed_by: reviewer, comments: comments || null }) }); setConfirming(null); await onComplete(); } catch (err) { setError(err instanceof Error ? err.message : "No pudimos registrar la decisión."); } finally { setSaving(false); } };
  const facts = review.evidence_snapshot.filter((item) => item.type !== "policy"); const policies = review.evidence_snapshot.filter((item) => item.type === "policy"); return <section className="review-detail panel"><div className="detail-header"><div><span className="status status--pending">Pendiente</span><h2>Revisión solicitada</h2></div><span className="request-id">{review.request_id}</span></div><div className="review-reason"><span className="eyebrow">MOTIVO</span><p>{review.reason}</p><p className="muted">Solicitada {formatDate(review.requested_at)}</p></div><div className="review-block"><span className="eyebrow">PREGUNTA</span><p>{review.question}</p></div><div className="review-block"><span className="eyebrow">RECOMMENDATION</span><pre className="data-preview">{JSON.stringify(review.recommendation_snapshot, null, 2)}</pre></div><EvidenceSection title={`Facts (${facts.length})`} items={facts} /><EvidenceSection title={`Policy evidence (${policies.length})`} items={policies} />{error && <div className="notice notice--error" role="alert">{error}</div>}<div className="decision-form"><label>Revisor<input value={reviewer} onChange={(e) => setReviewer(e.target.value)} required /></label><label>Comentarios<textarea value={comments} onChange={(e) => setComments(e.target.value)} rows={3} placeholder="Añade contexto para la auditoría (opcional)" /></label><div className="decision-actions"><button className="secondary-button" onClick={() => setConfirming("needs_information")}>Necesita información</button><button className="danger-button" onClick={() => setConfirming("reject")}>Rechazar</button><button className="primary-button" onClick={() => setConfirming("approve")}>Aprobar</button></div></div>{confirming && <div className="confirmation" role="dialog" aria-modal="true"><h3>¿Confirmar {statusLabel(confirming)}?</h3><p>Esta decisión se registrará en la auditoría y no podrá cambiarse desde esta pantalla.</p><div className="decision-actions"><button className="secondary-button" onClick={() => setConfirming(null)}>Cancelar</button><button className="primary-button" disabled={saving || !reviewer.trim()} onClick={() => void decide(confirming)}>{saving ? "Guardando…" : "Confirmar decisión"}</button></div></div>}</section>; }

function EvidenceSection({ title, items }: { title: string; items: Array<Record<string, unknown>> }) { return <div className="review-block"><span className="eyebrow">{title}</span>{items.length ? items.map((item, index) => <div className="evidence-card" key={index}><strong>{displayValue(item.title ?? item.document_key ?? item.provider ?? "Evidencia")}</strong><p className="evidence-meta">{displayValue(item.fragment ?? item.text ?? item.result)}</p>{typeof item.source_uri === "string" && <a className="source-link" href={item.source_uri} target="_blank" rel="noreferrer">Abrir fuente original ↗</a>}</div>) : <p className="muted">No hay evidencia en este snapshot.</p>}</div>; }
